### PR TITLE
read & preserve src file permission

### PR DESCRIPTION
**Pull request by drunkhacker**
This library is used in `phonegap-grunt` plugin, and I got a permission error when that plugin tries to run cordova hooks. See https://github.com/logankoester/grunt-phonegap/issues/13

I ran `npm test` after added my hunk, but didn't write new tests.

Thanks.

### CODE REVIEW

**Comment by bengourley** [comment]
Thanks for the contribution!

I added some tests and unfortunately it looks like it's not doing as expected. See my branch: https://github.com/bengourley/node-directory-copy/tree/drunkhacker-master. I could be doing something wrong in my tests, but it looks like it doesn't fully preserve the permissions when copying. (e.g copying `777` results in `755`).

If you can get tests to confirm your added feature I would be very happy to merge this. Cheers.

**Comment by drunkhacker** [comment]
Sorry for mess commits, but I ended up with set `umask` properly. I did keep my old code and just set umask for process generated files. Your 7 tests passed.

**Comment by drunkhacker** [comment]
FYI, github doesn't keep the permissions for certain files. Check it first before run the tests.

**Comment by logankoester** [comment]
Great to see this getting fixed! I'll leave https://github.com/logankoester/grunt-phonegap/issues/13 open until this is merged and then update the dependency. Thanks guys.

**Comment by bengourley** [comment]
I don't like the idea of setting and un-setting `process.umask` but I do want to get this fixed. Also git does maintain file permissons, so I don't know what's up there. When I get a moment I'll sort this out.

**Comment by bengourley** [comment]
Fixed in #2.

**Pull request closed without merging**
